exclude_patterns:
  - "**/node_modules/"
  - "**/*.d.ts"
  - "**/*.json"
  - "**/*.lock"
  - "**/*.enc"
  - "**/*.yml"
  - "**/.*.yml"
  - "**/*.md"
  - "**/.nycrc"
  - "**/.prettierrc"
  - "**/.gitignore"
  - "**/.editorconfig"
  - "**/.dockerignore"
  - "**/.babelrc"
  - "LICENSE"
  - "Dockerfile"
