exclude_patterns:
  - "**/node_modules/"
  - "**/*.d.ts"
  - "**/*.json"
  - "**/*.lock"
  - "**/*.enc"
  - "**/*.yml"
  - "**/.*.yml"
  - "**/*.md"
  - "**/*.css"
  - "**/*.svg"
  - "**/*.png"
  - "**/*.html"
  - "**/*.ico"
  - "**/*.enc"
  - "**/.*.enc"
  - "**/*.txt"
  - "**/*.tf"
  - "**/.nycrc"
  - "**/.prettierrc"
  - "**/.gitignore"
  - "**/.editorconfig"
  - "**/.dockerignore"
  - "**/.babelrc"
  - "**/index.ts"
  - "**/*.d.ts"
  - "LICENSE"
  - "Dockerfile"
